development:
  sessions:
    default:
      database: ro_site_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: ro_site_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

#MONGOLAB_URI: mongodb://heroku_app17339251:c2nc45cn9stlh0b9dc05fpqd7j@ds037468.mongolab.com:37468/heroku_app17339251
production:
  sessions:
    default:
      database: heroku_app17339251
      username: heroku_app17339251
      password: c2nc45cn9stlh0b9dc05fpqd7j
      hosts:
        - ds037468.mongolab.com:37468
      options:
        consistency: :strong
