development:
  sessions:
    default:
      database: ro_site_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong

test:
  sessions:
    default:
      database: ro_site_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

#mongodb://heroku_app6042021:vmnlajldupvpc6brhl58b6as90@ds039027.mongolab.com:39027/heroku_app6042021
# MONGOLAB_URI: mongodb://heroku_app6042021:vt4e997vlui7udaohkpc3fljdo@ds037758.mongolab.com:37758/heroku_app6042021
production:
  sessions:
    default:
      database: heroku_app6042021
      username: heroku_app6042021
      password: vt4e997vlui7udaohkpc3fljdo
      hosts:
        - ds039027.mongolab.com:39027
      options:
        consistency: :strong
